services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db
    command: [ "mongod", "--bind_ip_all" ]

volumes:
  mongo-data: